services:
  uav-1:
    build: ./swarm-node
    container_name: fm-uav-1
    environment:
      NODE_ID: "uav-1"

  uav-2:
    build: ./swarm-node
    container_name: fm-uav-2
    environment:
      NODE_ID: "uav-2"

  uav-3:
    build: ./swarm-node
    container_name: fm-uav-3
    environment:
      NODE_ID: "uav-3"

  uav-4:
    build: ./swarm-node
    container_name: fm-uav-4
    environment:
      NODE_ID: "uav-4"

  uav-5:
    build: ./swarm-node
    container_name: fm-uav-5
    environment:
      NODE_ID: "uav-5"
